### ISSUE TITLE
Item count (arrows/bombs) disappear from HUD when getting item from chest

### ISSUE THREAD

**Issue by scawful** [scawful/Oracle-of-Secrets#52]
![image](https://github.com/scawful/Oracle-of-Secrets/assets/47263509/dc3147fd-3174-463e-8ccf-a1815a1d7f90)
![image](https://github.com/scawful/Oracle-of-Secrets/assets/47263509/9ffb3ccd-1066-4633-99db-4a42f7ff4452)

**Comment by JaredBrian** [comment]
what a stupid specific bug lol. shouldn't be too hard to fix. opening the chest triggers the HUDUpdate function causing it to redraw the map and since the count isn't there in the default map it doesn't have anything else to trigger the draw count until you switch items again so it should be easy to just change where the HUDUpdate function is called slightly to call the count update as well.

**Comment by JaredBrian** [comment]
Fixed
