### ISSUE TITLE
if you try to fly to the village it will either be a black screen or glitchy graphics

### ISSUE THREAD

**Issue by 19Linkan90** [scawful/Oracle-of-Secrets#78]
if you try to fly to the village it will either be a black screen or glitchy graphics. See picture
![Screenshot_20240709-152312](https://github.com/scawful/Oracle-of-Secrets/assets/174653314/bd24e2b3-06e0-4cda-8818-9eacf7a21cd6)

**Comment by scawful** [comment]
This is partially fixed by putting the player into `LinkState_Default` if they are near the transition boundaries, however if you continue to press the directional buttons (basically forcing it) you can still cause scroll issues. If this continues to cause problems for gameplay I'll look at it again but overall I don't want to worry about it too much for now.
